name: Docker Python CI/CD

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger this action on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out the code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for building multi-platform Docker images

    - name: Build Docker image
      run: |
        docker build -t my-python-app .
        
