name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main   # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.A474668401763 }}.dkr.ecr.${{ secrets.AWus-east-1 }}.amazonaws.com/dockerimage:latest .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.474668401763 }}.dkr.ecr.${{ secrets.us-east-1}}.amazonaws.com/dockerimage:latest
