name: Docker Python CI/CD

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the 'main' branch
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for building multi-platform Docker images

    - name: Build Docker image
      run: |
        docker build -t dockerimages .
    
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1  # Authenticate Docker to AWS ECR m
      with:
        registry: public.ecr.aws

    - name: Tag Docker image for ECR
      run: |
        docker tag dockerimages:latest public.ecr.aws/474668401763/dockerimages

    - name: Push Docker image to AWS ECR
      run: |
        docker push public.ecr.aws/474668401763/dockerimages:latest



