name: Docker Python CI/CD

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the 'main' branch
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for building multi-platform Docker images

    - name: Build Docker image
      run: |
        docker build -t dockerimages .

    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1  # Authenticate Docker to AWS ECR Repo
      with:
        registry: private.ecr.aws
        region: us-east-1

    - name: Tag Docker image for ECR
      run: |
        docker tag dockerimages:latest 474668401763.dkr.ecr.us-east-1.amazonaws.com/docker-private:latest

    - name: Push Docker image to AWS ECR
      run: |
        docker push 474668401763.dkr.ecr.us-east-1.amazonaws.com/docker-private:latest

    # Step to register the ECS task definition with the latest image
    - name: Register ECS Task Definition
      run: |
        # Update the ECS task definition JSON with the new image
        sed -e 's|<IMAGE_URI>|474668401763.dkr.ecr.us-east-1.amazonaws.com/docker-private:latest|' task-definition.json > task-definition-updated.json

        # Register the ECS task definition
        aws ecs register-task-definition \
          --family my-ecs-task-definition \
          --cli-input-json file://task-definition-updated.json

    # Step to update ECS service to use the new task definition
    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster my-ecs-cluster \
          --service my-ecs-service \
          --task-definition my-ecs-task-definition \
          --desired-count 1  # Set the desired count of tasks (Fargate instances)
